device_type: "default.qubit"

batch_params:
  run_batch: False

data_params:
  data_type: "preset"

  pennylane_molecule_dataset:
    molecule_name: "H2"
    bond_length: 0.86

  manual_inputs:
    input_symbols: ["H", "H"]
    input_coordinates: [[0.3710, 0.0, 0.0], [-0.3710, 0.0, 0.0]]
    eigensolver_type: "numpy"
    graph_name: "H2"

circuit_params:
  ansatz_type: "hea"
  basis_state: "jordan_wigner"
  num_qubits: 4
  num_electrons: 2

  # Hardware efficient ansatz params
  num_layers: 3

  # Adaptive unitary coupled cluster ansatz params
  gradient_threshold: 0.00001
  partial_doubles_circuit_learning_rate: 0.5
  partial_doubles_circuit_epochs: 20

training_params:
  train_type: "torch"
  epochs: 50
  learning_rate: 0.01
  optimiser_type: "torch_adam"

visualisation_params:
  show_circuit: True
  show_loss_graph: False

data_export:
  export_graph: False
  export_parameters: False
