device_type: "default.qubit"

data_params:
  data_type: "manual_inputs"

  pennylane_molecule_dataset:
    molecule_name: "H2"
    bond_length: 0.7420

  manual_inputs:
    input_symbols: ["H", "H"]
    input_coordinates: [[0.3710, 0.0, 0.0], [-0.3710, 0.0, 0.0]]
    fci_energy: -1.174475

circuit_params:
  ansatz_type: "preset_pennylane_uccsd"
  num_qubits: 4
  num_electrons: 2

  # Hardware efficient ansatz params
  num_layers: 5

training_params:
  train_type: "torch"
  epochs: 2
  learning_rate: 0.01
  optimiser_type: "torch_adam"

visualisation_params:
  show_circuit: True
  show_loss_graph: True

data_export:
  export_graph: False
  export_parameters: False
