device_type: "default.qubit"

jit_enabled: False

batch_params:
  run_batch: False

data_params:
  data_type: "manual_inputs"

  pennylane_molecule_dataset:
    molecule_name: "LiH"
    bond_length: 0.9

  manual_inputs:
    input_symbols: ["H", "H"]
    input_coordinates: [[0.0, 0.0, 0.0], [-0.3710, 0.0, 0.0]]
    eigensolver_type: "numpy"
    graph_name: "H2"

circuit_params:
  ansatz_type: "adaptive_uccsd"
  basis_state: "jordan_wigner"
  num_qubits: 4
  num_electrons: 2

  # Hardware efficient ansatz params
  num_layers: 10

  # Adaptive unitary coupled cluster ansatz params
  gradient_threshold: 0.00001
  partial_doubles_circuit_learning_rate: 0.5
  partial_doubles_circuit_epochs: 20

training_params:
  train_type: "torch"
  epochs: 30
  learning_rate: 0.01
  optimiser_type: "torch_adam"

visualisation_params:
  show_circuit: False
  show_loss_graph: False

data_export:
  export_graph: True
  export_parameters: True
