device_type: "default.qubit"

data_params:
  pennylane_molecule_dataset:
    molecule_name: "BH3"
    bond_length: 1.189

circuit_params:
  ansatz_type: "hea"
  num_qubits: 14

  # Hardware efficient ansatz params
  num_layers: 3

training_params:
  epochs: 2

visualisation_params:
  show_circuit: False
  show_loss_graph: False
